### ISSUE TITLE
Deprecation Message Prevention

### ISSUE THREAD

**Issue by radzhome** [fcurella/django-markup-deprecated#1]
Any way this warning can be removed? Django seems to throw it even though the exception is caught from markup_deprecated. I think those that use this package are aware they are using something deprecated, its in the name.

```
projects/tassimo/site/lib/markup_deprecated/templatetags/markup.py:52: DeprecationWarning: The markdown filter has been deprecated
  category=DeprecationWarning)
```

**Comment by fcurella** [comment]
Hi @radlws,

You can filter out the warning by adding the following lines to your settings file:

``` python
import warnings

warnings.filterwarnings('ignore', category=DeprecationWarning, module='markup_deprecated')
```

**Comment by radzhome** [comment]
Thanks!
